In [1]:
import pandas as pd
import numpy as np

In [21]:
s = pd.read_csv('infer/song_ids.csv')
s

ids
0       381522
1       367057
2       297580
3        70490
4       126153
...        ...
679419  199118
679420  598783
679421   38370
679422  501459
679423   60089

[679424 rows x 1 columns]

In [26]:
a = pd.read_csv('infer/lyric_data_v2.tsv',sep='\t')
a[a.id == 608386]

id  song_id  song_name  \
105175  608386  5549381  우리가 있던 시간   
105472  608386  3899275  우리가 있던 시간   

                                                    lyric  artist  \
105175  생각한다 지난 날들 눈이 부시도록 아름다웠던 사라진다 뜨겁게 안아주던 네 손 끝 향...  스웨덴세탁소   
105472  생각한다 지난 날들 눈이 부시도록 아름다웠던 사라진다 뜨겁게 안아주던 네 손 끝 향...  스웨덴세탁소   

                genre      album  album_id   release  
105175  GN0500,GN0100  우리가 있던 시간   2149428  20120907  
105472  GN0500,GN0100  우리가 있던 시간   2149428  20120907

In [27]:
pd.read_csv('data/score_test_final.csv')

lyric   LABEL_0   LABEL_1  \
0       Feelings nothing more than feelings Trying to ...  0.321668  0.050276   
1       i feel alright now but don't know how to speak...  0.211127  0.195028   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...  0.946268  0.002743   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...  0.003543  0.029312   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...  0.239259  0.642580   
...                                                   ...       ...       ...   
112507  I'm standing on the edge And everything I know...  0.649147  0.047277   
112508  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  0.050572  0.032464   
112509  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  0.040549  0.041491   
112510  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  0.010605  0.014387   
112511  Nobody knows where she came from The tall-and-...  0.568110  0.061962   

         LABEL_2   LABEL_3   LABEL_4   LABEL_5  
0       0.000602  0.013912  0.100803  0.512739  
1       0.000657  0.017706  0.143551  0.431931  
2       0.003444  0.031837  0.003763  0.011944  
3       0.000641  0.821336  0.136336  0.008832  
4       0.001295  0.056139  0.040510  0.020217  
...          ...       ...       ...       ...  
112507  0.000647  0.006467  0.040910  0.255551  
112508  0.000567  0.006616  0.168869  0.740912  
112509  0.000643  0.071288  0.513658  0.332371  
112510  0.000957  0.872247  0.087935  0.013869  
112511  0.000684  0.005624  0.083877  0.279743  

[112512 rows x 7 columns]

In [61]:
sam = pd.read_csv('/home/wjswps/model/data/lyric_data_v4.csv')
sam.drop_duplicates(subset=['id'],inplace=True)
sam = sam.drop(columns='Unnamed: 0')
# sam[sam.id.duplicated()]


In [70]:
sam[sam.artist == '축하사절단'].index

Int64Index([   307,   1525,   1724,   2062,   2617,   3187,   4787,   4984,
              8223,   8626,
            ...
            101680, 101760, 103266, 103530, 106937, 107167, 107292, 108468,
            108933, 112059],
           dtype='int64', length=130)

In [72]:
sam = sam.drop(index=sam[sam.artist == '축하사절단'].index)
sam[sam.artist == '축하사절단']

Empty DataFrame
Columns: [lyric, id, song_id, song_name, artist, genre, album, album_id, release]
Index: []

In [79]:
#2015년 이후 노래만 보기
crsam = sam[sam.release >=20150000]
crsam.reset_index(inplace=True)

In [82]:
crsam = crsam.drop(columns='index')
crsam

lyric      id   song_id  \
0      그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9  30310140   
1      그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   5579388   
2      Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30  31808054   
3      먼지 속에 또 하루가 떠나고 숨기고 싶은 깊은 그림자에 기댄다 날려 사라지지 않는 ...      32  30477250   
4      You know I gotta love you our name is written ...      40  30256416   
...                                                  ...     ...       ...   
43957  I'm sitting here, writing this letter Hoping i...  153451  30223601   
43958  나극이 없는 산이면 난 달을 사곤 해 난 달을 사곤 해 난 달을 사곤 해 아무도 없...  153461  31274427   
43959  안녕 내 맘을 들킨 밤하늘에 똑똑똑 노크해 인사 건네요 말없이 걷는 동네 산책이 특...  153465  32194832   
43960  아 진짜 회사 가기 싫어 매일 매일 가슴이 답답해 싫어 하 근데 어쩌겠어 출근 하기...  153467  31812119   
43961  I'm standing on the edge And everything I know...  153503  30678873   

                                          song_name                   artist  \
0                                      사랑, 그대라는 멜로디                       진호   
1                               무얼 기다리나 (Feat. 조원선)                      이영훈   
2                                            9-TEEN                      세븐틴   
3                                                먼지                     에버루아   
4                       Your Love Could Start A War  The Unlikely Candidates   
...                                             ...                      ...   
43957                                       Maryann              New Edition   
43958                                무덤 (The Grave)                   사람12사람   
43959                                 walk in space                 하나 (구구단)   
43960                                   진짜 회사 가기 싫어                      장우람   
43961  Tomorrow Starts Today (Andi Mack Theme Song)        Sabrina Carpenter   

                      genre                                         album  \
0                    GN0100                             Pastel Reflection   
1             GN0500,GN0800                                    내가 부른 그림 2   
2      GN2500,GN1500,GN0200                                A-TEEN2 Part.2   
3                    GN1500                              비밀의 숲 OST Part.2   
4                    GN1000                                  Bed Of Liars   
...                     ...                                           ...   
43957                GN1300                        New Edition (Expanded)   
43958         GN0500,GN2600                                      빗물구름태풍태양   
43959  GN2500,GN1500,GN0100                            연남동 패밀리 OST part.1   
43960                GN1500    2019 회사 가기 싫어 (KBS 모큐멘터리 드라마) OST - Part.5   
43961         GN1500,GN0900  Tomorrow Starts Today (Andi Mack Theme Song)   

       album_id   release  
0      10047088  20170320  
1       2303168  20150205  
2      10286928  20190519  
3      10072040  20170617  
4      10039414  20170217  
...         ...       ...  
43957  10034455  20170120  
43958  10199004  20180829  
43959  10354762  20191122  
43960  10287679  20190521  
43961  10103797  20171020  

[43962 rows x 9 columns]

In [42]:
sam.to_csv('infer/infer_list.csv',index=False)

In [ ]:
#중복확인
def GetDifferences(df1, df2):
    df = pd.concat([df1, df2]).reset_index(drop=True)
    idx = [diff[0] for diff in df.groupby(list(df.columns)).groups.values() if len(diff) == 1]
    return df.reindex(idx)
d = GetDifferences(lyric[['lyric']],sample[['lyric']])
d.drop_duplicates(keep=False)

In [12]:
mel = np.load('/home/wjswps/model/data/inf_result.npy')
mel.shape

(112512, 6)

In [25]:
mel

array([[4.46542889e-01, 6.18077256e-03, 4.31429783e-07, 3.04179966e-01,
        1.37092814e-01, 1.06003143e-01],
       [4.62358147e-01, 4.27311519e-03, 1.13759924e-07, 2.97680616e-01,
        1.31611213e-01, 1.04076773e-01],
       [4.54116553e-01, 4.95393248e-03, 2.10201819e-07, 3.01343501e-01,
        1.33023873e-01, 1.06561877e-01],
       ...,
       [4.53480124e-01, 4.97103529e-03, 2.07018019e-07, 3.02088022e-01,
        1.32832125e-01, 1.06628433e-01],
       [4.62460756e-01, 4.75488696e-03, 1.69467640e-07, 2.90981680e-01,
        1.35397047e-01, 1.06405452e-01],
       [4.45696294e-01, 5.55884838e-03, 3.20366297e-07, 3.09897810e-01,
        1.33030191e-01, 1.05816498e-01]], dtype=float32)

In [26]:
lyric = pd.read_csv('/home/wjswps/model/data/score_test_final.csv')
lyric

lyric   LABEL_0   LABEL_1  \
0       Feelings nothing more than feelings Trying to ...  0.321668  0.050276   
1       i feel alright now but don't know how to speak...  0.211127  0.195028   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...  0.946268  0.002743   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...  0.003543  0.029312   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...  0.239259  0.642580   
...                                                   ...       ...       ...   
112507  I'm standing on the edge And everything I know...  0.649147  0.047277   
112508  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  0.050572  0.032464   
112509  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  0.040549  0.041491   
112510  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  0.010605  0.014387   
112511  Nobody knows where she came from The tall-and-...  0.568110  0.061962   

         LABEL_2   LABEL_3   LABEL_4   LABEL_5  
0       0.000602  0.013912  0.100803  0.512739  
1       0.000657  0.017706  0.143551  0.431931  
2       0.003444  0.031837  0.003763  0.011944  
3       0.000641  0.821336  0.136336  0.008832  
4       0.001295  0.056139  0.040510  0.020217  
...          ...       ...       ...       ...  
112507  0.000647  0.006467  0.040910  0.255551  
112508  0.000567  0.006616  0.168869  0.740912  
112509  0.000643  0.071288  0.513658  0.332371  
112510  0.000957  0.872247  0.087935  0.013869  
112511  0.000684  0.005624  0.083877  0.279743  

[112512 rows x 7 columns]

In [27]:
lyric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112512 entries, 0 to 112511
Data columns (total 7 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   lyric    112512 non-null  object 
 1   LABEL_0  112512 non-null  float64
 2   LABEL_1  112512 non-null  float64
 3   LABEL_2  112512 non-null  float64
 4   LABEL_3  112512 non-null  float64
 5   LABEL_4  112512 non-null  float64
 6   LABEL_5  112512 non-null  float64
dtypes: float64(6), object(1)
memory usage: 6.0+ MB


In [28]:
lyric['lyric_label'] =lyric.iloc[:,1:].values.tolist()
lyric['mel_label'] = mel.tolist()

In [29]:
lyric

lyric   LABEL_0   LABEL_1  \
0       Feelings nothing more than feelings Trying to ...  0.321668  0.050276   
1       i feel alright now but don't know how to speak...  0.211127  0.195028   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...  0.946268  0.002743   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...  0.003543  0.029312   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...  0.239259  0.642580   
...                                                   ...       ...       ...   
112507  I'm standing on the edge And everything I know...  0.649147  0.047277   
112508  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  0.050572  0.032464   
112509  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  0.040549  0.041491   
112510  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  0.010605  0.014387   
112511  Nobody knows where she came from The tall-and-...  0.568110  0.061962   

         LABEL_2   LABEL_3   LABEL_4   LABEL_5  \
0       0.000602  0.013912  0.100803  0.512739   
1       0.000657  0.017706  0.143551  0.431931   
2       0.003444  0.031837  0.003763  0.011944   
3       0.000641  0.821336  0.136336  0.008832   
4       0.001295  0.056139  0.040510  0.020217   
...          ...       ...       ...       ...   
112507  0.000647  0.006467  0.040910  0.255551   
112508  0.000567  0.006616  0.168869  0.740912   
112509  0.000643  0.071288  0.513658  0.332371   
112510  0.000957  0.872247  0.087935  0.013869   
112511  0.000684  0.005624  0.083877  0.279743   

                                              lyric_label  \
0       [0.3216681480407715, 0.0502759180963039, 0.000...   
1       [0.2111274302005767, 0.1950277388095855, 0.000...   
2       [0.9462682008743286, 0.0027434327639639, 0.003...   
3       [0.0035426244139671, 0.0293123461306095, 0.000...   
4       [0.239258661866188, 0.6425803303718567, 0.0012...   
...                                                   ...   
112507  [0.6491472721099854, 0.0472770929336547, 0.000...   
112508  [0.0505723059177398, 0.0324641726911067, 0.000...   
112509  [0.040549237281084, 0.041490864008665, 0.00064...   
112510  [0.0106050316244363, 0.0143865207210183, 0.000...   
112511  [0.5681098103523254, 0.0619623996317386, 0.000...   

                                                mel_label  
0       [0.446542888879776, 0.006180772557854652, 4.31...  
1       [0.46235814690589905, 0.004273115191608667, 1....  
2       [0.454116553068161, 0.004953932482749224, 2.10...  
3       [0.44969186186790466, 0.005605658516287804, 3....  
4       [0.36823996901512146, 0.04088175296783447, 0.0...  
...                                                   ...  
112507  [0.4598444700241089, 0.004870169796049595, 1.9...  
112508  [0.4552108347415924, 0.004968387074768543, 1.9...  
112509  [0.4534801244735718, 0.004971035290509462, 2.0...  
112510  [0.4624607563018799, 0.0047548869624733925, 1....  
112511  [0.44569629430770874, 0.0055588483810424805, 3...  

[112512 rows x 9 columns]

In [30]:
lyric = lyric[['lyric','lyric_label','mel_label']]
lyric

lyric  \
0       Feelings nothing more than feelings Trying to ...   
1       i feel alright now but don't know how to speak...   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...   
...                                                   ...   
112507  I'm standing on the edge And everything I know...   
112508  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...   
112509  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...   
112510  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...   
112511  Nobody knows where she came from The tall-and-...   

                                              lyric_label  \
0       [0.3216681480407715, 0.0502759180963039, 0.000...   
1       [0.2111274302005767, 0.1950277388095855, 0.000...   
2       [0.9462682008743286, 0.0027434327639639, 0.003...   
3       [0.0035426244139671, 0.0293123461306095, 0.000...   
4       [0.239258661866188, 0.6425803303718567, 0.0012...   
...                                                   ...   
112507  [0.6491472721099854, 0.0472770929336547, 0.000...   
112508  [0.0505723059177398, 0.0324641726911067, 0.000...   
112509  [0.040549237281084, 0.041490864008665, 0.00064...   
112510  [0.0106050316244363, 0.0143865207210183, 0.000...   
112511  [0.5681098103523254, 0.0619623996317386, 0.000...   

                                                mel_label  
0       [0.446542888879776, 0.006180772557854652, 4.31...  
1       [0.46235814690589905, 0.004273115191608667, 1....  
2       [0.454116553068161, 0.004953932482749224, 2.10...  
3       [0.44969186186790466, 0.005605658516287804, 3....  
4       [0.36823996901512146, 0.04088175296783447, 0.0...  
...                                                   ...  
112507  [0.4598444700241089, 0.004870169796049595, 1.9...  
112508  [0.4552108347415924, 0.004968387074768543, 1.9...  
112509  [0.4534801244735718, 0.004971035290509462, 2.0...  
112510  [0.4624607563018799, 0.0047548869624733925, 1....  
112511  [0.44569629430770874, 0.0055588483810424805, 3...  

[112512 rows x 3 columns]

In [43]:
meta = pd.read_csv('/home/wjswps/model/data/lyric_data_v4.csv')
meta = meta[['lyric','song_name','artist']]
meta

lyric  \
0       Feelings nothing more than feelings Trying to ...   
1       i feel alright now but don't know how to speak...   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...   
...                                                   ...   
112561  I'm standing on the edge And everything I know...   
112562  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...   
112563  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...   
112564  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...   
112565  Nobody knows where she came from The tall-and-...   

                                           song_name             artist  
0                                           Feelings    Various Artists  
1                      Lovers’ Leap (Feat. Qypthone)                애플스  
2                                       사랑, 그대라는 멜로디                 진호  
3                                무얼 기다리나 (Feat. 조원선)                이영훈  
4                                       창밖에 잠수교가 보인다                박영민  
...                                              ...                ...  
112561  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter  
112562                                  기타로 오토바이를 타자                산울림  
112563                                           장녹수                박윤경  
112564                                        다시 비가와                 코나  
112565                                        Astrud              Basia  

[112566 rows x 3 columns]

In [22]:
sample = pd.merge(lyric,meta,on='lyric')
sample

lyric   LABEL_0   LABEL_1  \
0       Feelings nothing more than feelings Trying to ...  0.321668  0.050276   
1       i feel alright now but don't know how to speak...  0.211127  0.195028   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...  0.946268  0.002743   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...  0.003543  0.029312   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...  0.239259  0.642580   
...                                                   ...       ...       ...   
112506  I'm standing on the edge And everything I know...  0.649147  0.047277   
112507  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  0.050572  0.032464   
112508  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  0.040549  0.041491   
112509  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  0.010605  0.014387   
112510  Nobody knows where she came from The tall-and-...  0.568110  0.061962   

         LABEL_2   LABEL_3   LABEL_4   LABEL_5  \
0       0.000602  0.013912  0.100803  0.512739   
1       0.000657  0.017706  0.143551  0.431931   
2       0.003444  0.031837  0.003763  0.011944   
3       0.000641  0.821336  0.136336  0.008832   
4       0.001295  0.056139  0.040510  0.020217   
...          ...       ...       ...       ...   
112506  0.000647  0.006467  0.040910  0.255551   
112507  0.000567  0.006616  0.168869  0.740912   
112508  0.000643  0.071288  0.513658  0.332371   
112509  0.000957  0.872247  0.087935  0.013869   
112510  0.000684  0.005624  0.083877  0.279743   

                                              lyric_label  \
0       [0.3216681480407715, 0.0502759180963039, 0.000...   
1       [0.2111274302005767, 0.1950277388095855, 0.000...   
2       [0.9462682008743286, 0.0027434327639639, 0.003...   
3       [0.0035426244139671, 0.0293123461306095, 0.000...   
4       [0.239258661866188, 0.6425803303718567, 0.0012...   
...                                                   ...   
112506  [0.6491472721099854, 0.0472770929336547, 0.000...   
112507  [0.0505723059177398, 0.0324641726911067, 0.000...   
112508  [0.040549237281084, 0.041490864008665, 0.00064...   
112509  [0.0106050316244363, 0.0143865207210183, 0.000...   
112510  [0.5681098103523254, 0.0619623996317386, 0.000...   

                                           song_name             artist  \
0                                           Feelings    Various Artists   
1                      Lovers’ Leap (Feat. Qypthone)                애플스   
2                                       사랑, 그대라는 멜로디                 진호   
3                                무얼 기다리나 (Feat. 조원선)                이영훈   
4                                       창밖에 잠수교가 보인다                박영민   
...                                              ...                ...   
112506  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter   
112507                                  기타로 오토바이를 타자                산울림   
112508                                           장녹수                박윤경   
112509                                        다시 비가와                 코나   
112510                                        Astrud              Basia   

         song_id  
0        4639910  
1        1657318  
2       30310140  
3        5579388  
4        3953129  
...          ...  
112506  30678873  
112507     91251  
112508   1455179  
112509    933221  
112510    337742  

[112511 rows x 11 columns]

In [13]:
#중복확인
def GetDifferences(df1, df2):
    df = pd.concat([df1, df2]).reset_index(drop=True)
    idx = [diff[0] for diff in df.groupby(list(df.columns)).groups.values() if len(diff) == 1]
    return df.reindex(idx)
d = GetDifferences(lyric[['lyric']],sample[['lyric']])
d.drop_duplicates(keep=False)

lyric
51657  Snow is falling from the sky in the middle of ...

In [45]:
result = pd.merge(lyric,meta,on='lyric')
result = result[['song_name','artist','lyric']]
result

song_name             artist  \
0                                           Feelings    Various Artists   
1                      Lovers’ Leap (Feat. Qypthone)                애플스   
2                                       사랑, 그대라는 멜로디                 진호   
3                                무얼 기다리나 (Feat. 조원선)                이영훈   
4                                       창밖에 잠수교가 보인다                박영민   
...                                              ...                ...   
112506  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter   
112507                                  기타로 오토바이를 타자                산울림   
112508                                           장녹수                박윤경   
112509                                        다시 비가와                 코나   
112510                                        Astrud              Basia   

                                                    lyric  
0       Feelings nothing more than feelings Trying to ...  
1       i feel alright now but don't know how to speak...  
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...  
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...  
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...  
...                                                   ...  
112506  I'm standing on the edge And everything I know...  
112507  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  
112508  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  
112509  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  
112510  Nobody knows where she came from The tall-and-...  

[112511 rows x 3 columns]

In [35]:
p = result[['song_id']]
p.to_csv('index.csv',index=False)

In [46]:
result.to_csv('/home/wjswps/model/data/meta_data.csv',index=False)

In [3]:
DB = pd.read_csv('/home/wjswps/model/data/DB.csv')
DB

song_name             artist  \
0                                           Feelings    Various Artists   
1                      Lovers’ Leap (Feat. Qypthone)                애플스   
2                                       사랑, 그대라는 멜로디                 진호   
3                                무얼 기다리나 (Feat. 조원선)                이영훈   
4                                       창밖에 잠수교가 보인다                박영민   
...                                              ...                ...   
112506  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter   
112507                                  기타로 오토바이를 타자                산울림   
112508                                           장녹수                박윤경   
112509                                        다시 비가와                 코나   
112510                                        Astrud              Basia   

                                                    lyric  \
0       Feelings nothing more than feelings Trying to ...   
1       i feel alright now but don't know how to speak...   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...   
...                                                   ...   
112506  I'm standing on the edge And everything I know...   
112507  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...   
112508  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...   
112509  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...   
112510  Nobody knows where she came from The tall-and-...   

                                              lyric_label  \
0       [0.3216681480407715, 0.0502759180963039, 0.000...   
1       [0.2111274302005767, 0.1950277388095855, 0.000...   
2       [0.9462682008743286, 0.0027434327639639, 0.003...   
3       [0.0035426244139671, 0.0293123461306095, 0.000...   
4       [0.239258661866188, 0.6425803303718567, 0.0012...   
...                                                   ...   
112506  [0.6491472721099854, 0.0472770929336547, 0.000...   
112507  [0.0505723059177398, 0.0324641726911067, 0.000...   
112508  [0.040549237281084, 0.041490864008665, 0.00064...   
112509  [0.0106050316244363, 0.0143865207210183, 0.000...   
112510  [0.5681098103523254, 0.0619623996317386, 0.000...   

                                                mel_label  
0       [0.446542888879776, 0.006180772557854652, 4.31...  
1       [0.46235814690589905, 0.004273115191608667, 1....  
2       [0.454116553068161, 0.004953932482749224, 2.10...  
3       [0.44969186186790466, 0.005605658516287804, 3....  
4       [0.36823996901512146, 0.04088175296783447, 0.0...  
...                                                   ...  
112506  [0.4598444700241089, 0.004870169796049595, 1.9...  
112507  [0.4552108347415924, 0.004968387074768543, 1.9...  
112508  [0.4534801244735718, 0.004971035290509462, 2.0...  
112509  [0.4624607563018799, 0.0047548869624733925, 1....  
112510  [0.44569629430770874, 0.0055588483810424805, 3...  

[112511 rows x 5 columns]

In [4]:
eval(DB.lyric_label[0])

[0.3216681480407715,
 0.0502759180963039,
 0.0006021789158694,
 0.0139119699597358,
 0.1008029356598854,
 0.512738823890686]

In [5]:
DB['lyric_label'] = DB.lyric_label.apply(lambda x: eval(x))
DB['mel_label'] = DB.mel_label.apply(lambda x: eval(x))

In [9]:
DB.lyric_label[0],DB.mel_label[9]

([0.3216681480407715,
  0.0502759180963039,
  0.0006021789158694,
  0.0139119699597358,
  0.1008029356598854,
  0.512738823890686],
 [0.46114543080329895,
  0.004892430268228054,
  1.843665842216069e-07,
  0.29223254323005676,
  0.13556204736232758,
  0.10616745054721832])

In [7]:
DB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112511 entries, 0 to 112510
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   song_name    112511 non-null  object
 1   artist       112511 non-null  object
 2   lyric        112511 non-null  object
 3   lyric_label  112511 non-null  object
 4   mel_label    112511 non-null  object
dtypes: object(5)
memory usage: 4.3+ MB


In [13]:
DB.to_csv('/home/wjswps/model/data/database.csv',index=False)

In [1]:
data = pd.read_csv('/home/wjswps/model/data/database.csv')
data

NameError: name 'pd' is not defined

In [37]:
data['lyric_label'] = data.lyric_label.apply(lambda x: np.array(eval(x)).reshape(1,-1))
data['mel_label'] = data.mel_label.apply(lambda x: np.array(eval(x)).reshape(1,-1))

In [38]:

def weighted_sum(lyrics,mels,a=.5,b=.5):

    fin_vec = np.empty((0,6))
    for i in range(len(mels)):
        wei_vec = a*lyrics[i] + b*mels[i]
        # wei_vec = wei_vec.reshape(1,6)
        fin_vec = np.vstack((fin_vec,wei_vec))
    return fin_vec
vectors = weighted_sum(data.lyric_label,data.mel_label)

In [48]:
vectors

array([[3.84105518e-01, 2.82283453e-02, 3.01305173e-04, 1.59045968e-01,
        1.18947875e-01, 3.09370983e-01],
       [3.36742789e-01, 9.96504270e-02, 3.28564853e-04, 1.57693444e-01,
        1.37581132e-01, 2.68003657e-01],
       [7.00192377e-01, 3.84868262e-03, 1.72233847e-03, 1.66590417e-01,
        6.83933388e-02, 5.92528367e-02],
       ...,
       [2.47014681e-01, 2.32309496e-02, 3.21767600e-04, 1.86687965e-01,
        3.23244847e-01, 2.19499744e-01],
       [2.36532894e-01, 9.57070384e-03, 4.78803571e-04, 5.81614450e-01,
        1.11665808e-01, 6.01373133e-02],
       [5.06903052e-01, 3.37606240e-02, 3.41990755e-04, 1.57760837e-01,
        1.08453680e-01, 1.92779787e-01]])

In [42]:
np.save('label_score.npy',vectors)

In [52]:
vectors[1]

array([3.36742789e-01, 9.96504270e-02, 3.28564853e-04, 1.57693444e-01,
       1.37581132e-01, 2.68003657e-01])

In [60]:
meta = pd.read_csv('data/meta_data.csv')

In [6]:
m = np.load('data/label_score.npy')
m.dtype

dtype('float64')

In [9]:
m = m.astype('float16')
np.save('label_score16.npy',m)

## 가중합 데이터 만들기 및 가사npy 뽑기

In [83]:
crsam

lyric      id   song_id  \
0      그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9  30310140   
1      그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   5579388   
2      Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30  31808054   
3      먼지 속에 또 하루가 떠나고 숨기고 싶은 깊은 그림자에 기댄다 날려 사라지지 않는 ...      32  30477250   
4      You know I gotta love you our name is written ...      40  30256416   
...                                                  ...     ...       ...   
43957  I'm sitting here, writing this letter Hoping i...  153451  30223601   
43958  나극이 없는 산이면 난 달을 사곤 해 난 달을 사곤 해 난 달을 사곤 해 아무도 없...  153461  31274427   
43959  안녕 내 맘을 들킨 밤하늘에 똑똑똑 노크해 인사 건네요 말없이 걷는 동네 산책이 특...  153465  32194832   
43960  아 진짜 회사 가기 싫어 매일 매일 가슴이 답답해 싫어 하 근데 어쩌겠어 출근 하기...  153467  31812119   
43961  I'm standing on the edge And everything I know...  153503  30678873   

                                          song_name                   artist  \
0                                      사랑, 그대라는 멜로디                       진호   
1                               무얼 기다리나 (Feat. 조원선)                      이영훈   
2                                            9-TEEN                      세븐틴   
3                                                먼지                     에버루아   
4                       Your Love Could Start A War  The Unlikely Candidates   
...                                             ...                      ...   
43957                                       Maryann              New Edition   
43958                                무덤 (The Grave)                   사람12사람   
43959                                 walk in space                 하나 (구구단)   
43960                                   진짜 회사 가기 싫어                      장우람   
43961  Tomorrow Starts Today (Andi Mack Theme Song)        Sabrina Carpenter   

                      genre                                         album  \
0                    GN0100                             Pastel Reflection   
1             GN0500,GN0800                                    내가 부른 그림 2   
2      GN2500,GN1500,GN0200                                A-TEEN2 Part.2   
3                    GN1500                              비밀의 숲 OST Part.2   
4                    GN1000                                  Bed Of Liars   
...                     ...                                           ...   
43957                GN1300                        New Edition (Expanded)   
43958         GN0500,GN2600                                      빗물구름태풍태양   
43959  GN2500,GN1500,GN0100                            연남동 패밀리 OST part.1   
43960                GN1500    2019 회사 가기 싫어 (KBS 모큐멘터리 드라마) OST - Part.5   
43961         GN1500,GN0900  Tomorrow Starts Today (Andi Mack Theme Song)   

       album_id   release  
0      10047088  20170320  
1       2303168  20150205  
2      10286928  20190519  
3      10072040  20170617  
4      10039414  20170217  
...         ...       ...  
43957  10034455  20170120  
43958  10199004  20180829  
43959  10354762  20191122  
43960  10287679  20190521  
43961  10103797  20171020  

[43962 rows x 9 columns]

In [85]:
import pandas as pd
lyric = pd.read_csv('infer/dim512_score.csv')
lyric

lyric      id   song_id  \
0       Feelings nothing more than feelings Trying to ...       0   4639910   
1       i feel alright now but don't know how to speak...       8   1657318   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9  30310140   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   5579388   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...      29   3953129   
...                                                   ...     ...       ...   
109045  I'm standing on the edge And everything I know...  153503  30678873   
109046  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  153507     91251   
109047  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  153522   1455179   
109048  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  153545    933221   
109049  Nobody knows where she came from The tall-and-...  153548    337742   

                                           song_name             artist  \
0                                           Feelings    Various Artists   
1                      Lovers’ Leap (Feat. Qypthone)                애플스   
2                                       사랑, 그대라는 멜로디                 진호   
3                                무얼 기다리나 (Feat. 조원선)                이영훈   
4                                       창밖에 잠수교가 보인다                박영민   
...                                              ...                ...   
109045  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter   
109046                                  기타로 오토바이를 타자                산울림   
109047                                           장녹수                박윤경   
109048                                        다시 비가와                 코나   
109049                                        Astrud              Basia   

                genre                                        lyric_label  
0              GN0900  [0.08386170864105225, 0.03447858244180679, 0.0...  
1              GN0300  [0.04266268014907837, 0.043162502348423004, 0....  
2              GN0100  [0.1833738386631012, 0.005769825074821711, 0.2...  
3       GN0500,GN0800  [0.002565082861110568, 0.006234192289412022, 0...  
4              GN1500  [0.016898691654205322, 0.1526065468788147, 0.0...  
...               ...                                                ...  
109045  GN1500,GN0900  [0.5777709484100342, 0.027232283726334572, 0.0...  
109046         GN0600  [0.13839325308799744, 0.03238226845860481, 0.0...  
109047         GN0700  [0.01770848035812378, 0.009806573390960693, 0....  
109048         GN0100  [0.003340568859130144, 0.004614077042788267, 0...  
109049         GN0900  [0.4817579984664917, 0.055723365396261215, 0.0...  

[109050 rows x 7 columns]

In [35]:
import numpy as np
mel = np.load('infer/mel.npy')
mel

array([[0.09690215, 0.01703895, 0.04080429, 0.77372783, 0.02106589,
        0.05046088],
       [0.10069682, 0.02590643, 0.07402409, 0.7130443 , 0.02185237,
        0.06447601],
       [0.05976965, 0.00968204, 0.09559699, 0.8094395 , 0.00977854,
        0.01573324],
       ...,
       [0.10780559, 0.0234835 , 0.04936424, 0.7271975 , 0.0234752 ,
        0.06867397],
       [0.12444647, 0.03262126, 0.04967552, 0.67468446, 0.02804896,
        0.09052343],
       [0.17202409, 0.02690762, 0.07345901, 0.61805356, 0.02707268,
        0.08248309]], dtype=float32)

In [43]:
mel.shape

(109050, 6)

In [55]:

def weighted_sum(lyrics,mels,a=.5,b=.5):

    fin_vec = np.empty((0,6))
    for i in range(len(mels)):
        wei_vec = a*lyrics[i] + b*mels[i]
        # wei_vec = wei_vec.reshape(1,6)
        fin_vec = np.vstack((fin_vec,wei_vec))
    return fin_vec
vectors = weighted_sum(vec,mel)

In [57]:
vectors.shape

(109050, 6)

In [58]:
vectors[0],vec[0],mel[0]

(array([0.09038193, 0.02575876, 0.03379629, 0.76131874, 0.02433486,
        0.06440943]),
 array([0.08386171, 0.03447858, 0.0267883 , 0.74890965, 0.02760383,
        0.07835799]),
 array([0.09690215, 0.01703895, 0.04080429, 0.77372783, 0.02106589,
        0.05046088], dtype=float32))

In [59]:
np.save('lyric_mel.npy',vectors)

In [60]:
np.load('infer/lyric_mel.npy')

array([[0.09038193, 0.02575876, 0.03379629, 0.76131874, 0.02433486,
        0.06440943],
       [0.07167975, 0.03453446, 0.04154283, 0.74022946, 0.03663309,
        0.07538041],
       [0.12157174, 0.00772593, 0.165467  , 0.68033141, 0.01147165,
        0.01343222],
       ...,
       [0.06275704, 0.01664504, 0.02893882, 0.811104  , 0.02696777,
        0.05358734],
       [0.06389352, 0.01861767, 0.02756041, 0.82481563, 0.01822172,
        0.04689111],
       [0.32689104, 0.04131549, 0.05054139, 0.38347829, 0.03099977,
        0.16677401]])

In [84]:
mel

array([[0.09690215, 0.01703895, 0.04080429, 0.77372783, 0.02106589,
        0.05046088],
       [0.10069682, 0.02590643, 0.07402409, 0.7130443 , 0.02185237,
        0.06447601],
       [0.05976965, 0.00968204, 0.09559699, 0.8094395 , 0.00977854,
        0.01573324],
       ...,
       [0.10780559, 0.0234835 , 0.04936424, 0.7271975 , 0.0234752 ,
        0.06867397],
       [0.12444647, 0.03262126, 0.04967552, 0.67468446, 0.02804896,
        0.09052343],
       [0.17202409, 0.02690762, 0.07345901, 0.61805356, 0.02707268,
        0.08248309]], dtype=float32)

In [83]:
mel_data = pd.DataFrame(mel)
mel_data

0         1         2         3         4         5
0       0.096902  0.017039  0.040804  0.773728  0.021066  0.050461
1       0.100697  0.025906  0.074024  0.713044  0.021852  0.064476
2       0.059770  0.009682  0.095597  0.809439  0.009779  0.015733
3       0.065277  0.012100  0.081089  0.807548  0.012263  0.021722
4       0.124324  0.046833  0.040421  0.599785  0.041376  0.147261
...          ...       ...       ...       ...       ...       ...
109045  0.221239  0.027166  0.090387  0.548268  0.027294  0.085646
109046  0.160045  0.031641  0.043310  0.605904  0.050245  0.108855
109047  0.107806  0.023483  0.049364  0.727198  0.023475  0.068674
109048  0.124446  0.032621  0.049676  0.674684  0.028049  0.090523
109049  0.172024  0.026908  0.073459  0.618054  0.027073  0.082483

[109050 rows x 6 columns]

In [86]:
lyric['mel_label'] = mel_data.values.tolist()

In [87]:
lyric = lyric[lyric.artist!='Various Artists']
lyric

lyric      id   song_id  \
1       i feel alright now but don't know how to speak...       8   1657318   
2       그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9  30310140   
3       그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   5579388   
4       너를보면 나는 잠이와 이상하다 그치 잠이오면 나는 잠을자 이상하다 그치 자면서 너에...      29   3953129   
5       Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30  31808054   
...                                                   ...     ...       ...   
109045  I'm standing on the edge And everything I know...  153503  30678873   
109046  기타로 오토바이 타자 기타로 오토바이 타자 기타로 오토바이 타자 타자 오토바이로 기...  153507     91251   
109047  가는 세월 바람 타고 흘러가는 저 구름아 수많은 사연 담아 가는 곳이 어드메냐 구중...  153522   1455179   
109048  누구도 원했던건 아니지만 어느새 시간은 여기까지 우릴 데리고 왔지 어떻게 지내왔는지...  153545    933221   
109049  Nobody knows where she came from The tall-and-...  153548    337742   

                                           song_name             artist  \
1                      Lovers’ Leap (Feat. Qypthone)                애플스   
2                                       사랑, 그대라는 멜로디                 진호   
3                                무얼 기다리나 (Feat. 조원선)                이영훈   
4                                       창밖에 잠수교가 보인다                박영민   
5                                             9-TEEN                세븐틴   
...                                              ...                ...   
109045  Tomorrow Starts Today (Andi Mack Theme Song)  Sabrina Carpenter   
109046                                  기타로 오토바이를 타자                산울림   
109047                                           장녹수                박윤경   
109048                                        다시 비가와                 코나   
109049                                        Astrud              Basia   

                       genre  \
1                     GN0300   
2                     GN0100   
3              GN0500,GN0800   
4                     GN1500   
5       GN2500,GN1500,GN0200   
...                      ...   
109045         GN1500,GN0900   
109046                GN0600   
109047                GN0700   
109048                GN0100   
109049                GN0900   

                                              lyric_label  \
1       [0.04266268014907837, 0.043162502348423004, 0....   
2       [0.1833738386631012, 0.005769825074821711, 0.2...   
3       [0.002565082861110568, 0.006234192289412022, 0...   
4       [0.016898691654205322, 0.1526065468788147, 0.0...   
5       [0.1330070048570633, 0.00823077093809843, 0.34...   
...                                                   ...   
109045  [0.5777709484100342, 0.027232283726334572, 0.0...   
109046  [0.13839325308799744, 0.03238226845860481, 0.0...   
109047  [0.01770848035812378, 0.009806573390960693, 0....   
109048  [0.003340568859130144, 0.004614077042788267, 0...   
109049  [0.4817579984664917, 0.055723365396261215, 0.0...   

                                                mel_label  
1       [0.10069681704044342, 0.025906426832079887, 0....  
2       [0.0597696490585804, 0.00968204066157341, 0.09...  
3       [0.06527718156576157, 0.012099635787308216, 0....  
4       [0.12432417273521423, 0.04683331400156021, 0.0...  
5       [0.13352879881858826, 0.017504772171378136, 0....  
...                                                   ...  
109045  [0.22123853862285614, 0.027166282758116722, 0....  
109046  [0.16004452109336853, 0.03164103254675865, 0.0...  
109047  [0.10780559480190277, 0.02348349802196026, 0.0...  
109048  [0.12444646656513214, 0.03262126073241234, 0.0...  
109049  [0.17202408611774445, 0.02690761722624302, 0.0...  

[108333 rows x 8 columns]

In [88]:
lyric = lyric[~lyric.genre.str.contains('GN2200')]
lyric[lyric.genre.str.contains('GN2200')]

Empty DataFrame
Columns: [lyric, id, song_id, song_name, artist, genre, lyric_label, mel_label]
Index: []

In [100]:
crsam = pd.read_csv('2015meta.csv')
crsam

lyric      id  \
0      그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9   
1      그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   
2      Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30   
3      먼지 속에 또 하루가 떠나고 숨기고 싶은 깊은 그림자에 기댄다 날려 사라지지 않는 ...      32   
4      You know I gotta love you our name is written ...      40   
...                                                  ...     ...   
43100  I'm sitting here, writing this letter Hoping i...  153451   
43101  나극이 없는 산이면 난 달을 사곤 해 난 달을 사곤 해 난 달을 사곤 해 아무도 없...  153461   
43102  안녕 내 맘을 들킨 밤하늘에 똑똑똑 노크해 인사 건네요 말없이 걷는 동네 산책이 특...  153465   
43103  아 진짜 회사 가기 싫어 매일 매일 가슴이 답답해 싫어 하 근데 어쩌겠어 출근 하기...  153467   
43104  I'm standing on the edge And everything I know...  153503   

                                          song_name                   artist  \
0                                      사랑, 그대라는 멜로디                       진호   
1                               무얼 기다리나 (Feat. 조원선)                      이영훈   
2                                            9-TEEN                      세븐틴   
3                                                먼지                     에버루아   
4                       Your Love Could Start A War  The Unlikely Candidates   
...                                             ...                      ...   
43100                                       Maryann              New Edition   
43101                                무덤 (The Grave)                   사람12사람   
43102                                 walk in space                 하나 (구구단)   
43103                                   진짜 회사 가기 싫어                      장우람   
43104  Tomorrow Starts Today (Andi Mack Theme Song)        Sabrina Carpenter   

                      genre   release  
0                    GN0100  20170320  
1             GN0500,GN0800  20150205  
2      GN2500,GN1500,GN0200  20190519  
3                    GN1500  20170617  
4                    GN1000  20170217  
...                     ...       ...  
43100                GN1300  20170120  
43101         GN0500,GN2600  20180829  
43102  GN2500,GN1500,GN0100  20191122  
43103                GN1500  20190521  
43104         GN1500,GN0900  20171020  

[43105 rows x 6 columns]

In [101]:
lyric = lyric[['id','lyric_label','mel_label']]

lyric

id                                        lyric_label  \
1            8  [0.04266268014907837, 0.043162502348423004, 0....   
2            9  [0.1833738386631012, 0.005769825074821711, 0.2...   
3           19  [0.002565082861110568, 0.006234192289412022, 0...   
4           29  [0.016898691654205322, 0.1526065468788147, 0.0...   
5           30  [0.1330070048570633, 0.00823077093809843, 0.34...   
...        ...                                                ...   
109045  153503  [0.5777709484100342, 0.027232283726334572, 0.0...   
109046  153507  [0.13839325308799744, 0.03238226845860481, 0.0...   
109047  153522  [0.01770848035812378, 0.009806573390960693, 0....   
109048  153545  [0.003340568859130144, 0.004614077042788267, 0...   
109049  153548  [0.4817579984664917, 0.055723365396261215, 0.0...   

                                                mel_label  
1       [0.10069681704044342, 0.025906426832079887, 0....  
2       [0.0597696490585804, 0.00968204066157341, 0.09...  
3       [0.06527718156576157, 0.012099635787308216, 0....  
4       [0.12432417273521423, 0.04683331400156021, 0.0...  
5       [0.13352879881858826, 0.017504772171378136, 0....  
...                                                   ...  
109045  [0.22123853862285614, 0.027166282758116722, 0....  
109046  [0.16004452109336853, 0.03164103254675865, 0.0...  
109047  [0.10780559480190277, 0.02348349802196026, 0.0...  
109048  [0.12444646656513214, 0.03262126073241234, 0.0...  
109049  [0.17202408611774445, 0.02690761722624302, 0.0...  

[108024 rows x 3 columns]

In [102]:
mer = crsam.merge(lyric,on='id')

In [103]:
mer.columns

Index(['lyric', 'id', 'song_name', 'artist', 'genre', 'release', 'lyric_label',
       'mel_label'],
      dtype='object')

In [104]:
mer

lyric      id  \
0      그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9   
1      그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   
2      Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30   
3      먼지 속에 또 하루가 떠나고 숨기고 싶은 깊은 그림자에 기댄다 날려 사라지지 않는 ...      32   
4      You know I gotta love you our name is written ...      40   
...                                                  ...     ...   
42834  I'm sitting here, writing this letter Hoping i...  153451   
42835  나극이 없는 산이면 난 달을 사곤 해 난 달을 사곤 해 난 달을 사곤 해 아무도 없...  153461   
42836  안녕 내 맘을 들킨 밤하늘에 똑똑똑 노크해 인사 건네요 말없이 걷는 동네 산책이 특...  153465   
42837  아 진짜 회사 가기 싫어 매일 매일 가슴이 답답해 싫어 하 근데 어쩌겠어 출근 하기...  153467   
42838  I'm standing on the edge And everything I know...  153503   

                                          song_name                   artist  \
0                                      사랑, 그대라는 멜로디                       진호   
1                               무얼 기다리나 (Feat. 조원선)                      이영훈   
2                                            9-TEEN                      세븐틴   
3                                                먼지                     에버루아   
4                       Your Love Could Start A War  The Unlikely Candidates   
...                                             ...                      ...   
42834                                       Maryann              New Edition   
42835                                무덤 (The Grave)                   사람12사람   
42836                                 walk in space                 하나 (구구단)   
42837                                   진짜 회사 가기 싫어                      장우람   
42838  Tomorrow Starts Today (Andi Mack Theme Song)        Sabrina Carpenter   

                      genre   release  \
0                    GN0100  20170320   
1             GN0500,GN0800  20150205   
2      GN2500,GN1500,GN0200  20190519   
3                    GN1500  20170617   
4                    GN1000  20170217   
...                     ...       ...   
42834                GN1300  20170120   
42835         GN0500,GN2600  20180829   
42836  GN2500,GN1500,GN0100  20191122   
42837                GN1500  20190521   
42838         GN1500,GN0900  20171020   

                                             lyric_label  \
0      [0.1833738386631012, 0.005769825074821711, 0.2...   
1      [0.002565082861110568, 0.006234192289412022, 0...   
2      [0.1330070048570633, 0.00823077093809843, 0.34...   
3      [0.003276160918176174, 0.005410064943134785, 0...   
4      [0.42398878931999207, 0.04754579812288284, 0.0...   
...                                                  ...   
42834  [0.31094467639923096, 0.022558342665433884, 0....   
42835  [0.004601599648594856, 0.004508213605731726, 0...   
42836  [0.06018847972154617, 0.04416966065764427, 0.0...   
42837  [0.0015070713125169277, 0.006543352268636227, ...   
42838  [0.5777709484100342, 0.027232283726334572, 0.0...   

                                               mel_label  
0      [0.0597696490585804, 0.00968204066157341, 0.09...  
1      [0.06527718156576157, 0.012099635787308216, 0....  
2      [0.13352879881858826, 0.017504772171378136, 0....  
3      [0.06894802302122116, 0.01271568238735199, 0.0...  
4      [0.18343688547611237, 0.025227071717381477, 0....  
...                                                  ...  
42834  [0.17909084260463715, 0.032948076725006104, 0....  
42835  [0.16944363713264465, 0.03393063321709633, 0.0...  
42836  [0.13827858865261078, 0.011515858583152294, 0....  
42837  [0.12664374709129333, 0.01738530583679676, 0.0...  
42838  [0.22123853862285614, 0.027166282758116722, 0....  

[42839 rows x 8 columns]

In [112]:
np.array(mer.lyric_label[0]).reshape(1,-1)

array([[0.18337384, 0.00576983, 0.235337  , 0.55122334, 0.01316476,
        0.01113121]])

In [113]:
mer['lyric_label'] = mer.lyric_label.apply(lambda x: np.array(x).reshape(1,-1))
mer['mel_label'] = mer.mel_label.apply(lambda x: np.array(x).reshape(1,-1))

In [114]:
mer.lyric_label[0]

array([[0.18337384, 0.00576983, 0.235337  , 0.55122334, 0.01316476,
        0.01113121]])

In [115]:
svec = np.empty((0,6))
mvec = np.empty((0,6))
for i in range(len(mer)):
    svec = np.vstack((svec,mer.lyric_label[i]))
    mvec = np.vstack((mvec,mer.mel_label[i]))
mvec,svec

(array([[0.05976965, 0.00968204, 0.09559699, 0.80943948, 0.00977854,
         0.01573324],
        [0.06527718, 0.01209964, 0.08108936, 0.80754834, 0.01226337,
         0.0217221 ],
        [0.1335288 , 0.01750477, 0.09377782, 0.67040157, 0.04163589,
         0.04315117],
        ...,
        [0.13827859, 0.01151586, 0.1550115 , 0.65593052, 0.01642979,
         0.02283372],
        [0.12664375, 0.01738531, 0.07643475, 0.70950919, 0.02594169,
         0.0440854 ],
        [0.22123854, 0.02716628, 0.09038746, 0.54826802, 0.0272937 ,
         0.08564606]]),
 array([[1.83373839e-01, 5.76982507e-03, 2.35337004e-01, 5.51223338e-01,
         1.31647633e-02, 1.11312103e-02],
        [2.56508286e-03, 6.23419229e-03, 8.22220370e-03, 9.73222077e-01,
         6.50918763e-03, 3.24728922e-03],
        [1.33007005e-01, 8.23077094e-03, 3.42233300e-01, 4.96810466e-01,
         9.04574897e-03, 1.06726456e-02],
        ...,
        [6.01884797e-02, 4.41696607e-02, 3.93607654e-02, 8.40465069e-01,
        

In [116]:
np.save('infer/2015lyric',svec)
np.save('infer/2015mel',mvec)

In [117]:

def weighted_sum(lyrics,mels,a=.5,b=.5):

    fin_vec = np.empty((0,6))
    for i in range(len(mels)):
        wei_vec = a*lyrics[i] + b*mels[i]
        # wei_vec = wei_vec.reshape(1,6)
        fin_vec = np.vstack((fin_vec,wei_vec))
    return fin_vec
vector = weighted_sum(svec,mvec)

In [1]:
me = mer[['lyric','id','song_name', 'artist', 'genre','release']]
me.to_csv('infer/2015meta.csv',index=False,encoding='sig-utf-8')

NameError: name 'mer' is not defined

In [119]:
np.save('infer/2015lyric_mel',vector)

## 데이터 처리 추가작업
어린이 노래 로또,생일축하등 cut

In [32]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 20)

In [33]:
meta = pd.read_csv('2015meta.csv')
meta.head()

lyric      id  \
0      그대 스치는 바람처럼 불어와서 내 곁에 머무른 사람 나도 몰래 내쉬는 숨처럼 익숙해...       9   
1      그냥 생각 없이 이렇다 할 뜻도 없이 쉼 없이 웃으며 떠드는 이들을 가만히 두리번거...      19   
2      Youth 우리 함께 걷는 우리의 발걸음 소중한 시간 너와 함께라 용기를 낼 수 있...      30   
3      먼지 속에 또 하루가 떠나고 숨기고 싶은 깊은 그림자에 기댄다 날려 사라지지 않는 ...      32   
4      You know I gotta love you our name is written ...      40   
...                                                  ...     ...   
43100  I'm sitting here, writing this letter Hoping i...  153451   
43101  나극이 없는 산이면 난 달을 사곤 해 난 달을 사곤 해 난 달을 사곤 해 아무도 없...  153461   
43102  안녕 내 맘을 들킨 밤하늘에 똑똑똑 노크해 인사 건네요 말없이 걷는 동네 산책이 특...  153465   
43103  아 진짜 회사 가기 싫어 매일 매일 가슴이 답답해 싫어 하 근데 어쩌겠어 출근 하기...  153467   
43104  I'm standing on the edge And everything I know...  153503   

                                          song_name                   artist  \
0                                      사랑, 그대라는 멜로디                       진호   
1                               무얼 기다리나 (Feat. 조원선)                      이영훈   
2                                            9-TEEN                      세븐틴   
3                                                먼지                     에버루아   
4                       Your Love Could Start A War  The Unlikely Candidates   
...                                             ...                      ...   
43100                                       Maryann              New Edition   
43101                                무덤 (The Grave)                   사람12사람   
43102                                 walk in space                 하나 (구구단)   
43103                                   진짜 회사 가기 싫어                      장우람   
43104  Tomorrow Starts Today (Andi Mack Theme Song)        Sabrina Carpenter   

                      genre   release  
0                    GN0100  20170320  
1             GN0500,GN0800  20150205  
2      GN2500,GN1500,GN0200  20190519  
3                    GN1500  20170617  
4                    GN1000  20170217  
...                     ...       ...  
43100                GN1300  20170120  
43101         GN0500,GN2600  20180829  
43102  GN2500,GN1500,GN0100  20191122  
43103                GN1500  20190521  
43104         GN1500,GN0900  20171020  

[43105 rows x 6 columns]

In [5]:
meta[meta.artist=='Various Artists']

lyric      id  \
236    쏟아지는 해! 해! 피! 온 세상에 가득 내리는 꿈의 빗방울 너의 마음이 우리 마음...    3064   
1782   Some say love it is a river that drowns the te...   19090   
2072   잘 먹겠습니다! 우리 모두의 마음을 하나로 모아 꿈과 음표의 풀코스 함께 만들어요 ...   22799   
3146   I love your world Where the winners might be s...  172693   
3525   You take a flight to eastern world Oh don't te...  177978   
...                                                  ...     ...   
39698  너에게로 또다시 돌아오기까지가 왜 이리 힘들었을까 이제 나는 알았어 내가 죽는날까지...  100868   
41324  표정 없는 가면 무도회 그대의 환한 미소 어두웠던 지난 시간 속 나를 구해주었어 내...  123675   
41347  공주님들 마음 Vanity 비밀의 Colon 잊지 않았지? 파우치 속 눈물과 Sug...  123951   
41820  머리에 장식한 Moonlight 한밤중에 Parade 꿈속으로 찾아온 Fall in...  131566   
42920  Hey! Queen! Get music! Masterpiece! 돌아가지 않아 아무...  149181   

                            song_name           artist          genre  \
236                쏟아지는 Happy! (해피레인)  Various Artists  GN1500,GN2200   
1782                         The Rose  Various Artists         GN0900   
2072   Sweet Time Cooking Magic (김아람)  Various Artists  GN1500,GN2200   
3146                             Yeti  Various Artists         GN0900   
3525                       Tokyo Town  Various Artists         GN0900   
...                               ...              ...            ...   
39698                        너에게로 또다시  Various Artists         GN0100   
41324                     Pride (신도하)  Various Artists  GN1500,GN2200   
41347              Vanity♥Colon (송온유)  Various Artists  GN1500,GN2200   
41820              Mirage Jet (스프라우츠)  Various Artists  GN1500,GN2200   
42920                 Get Music! (류빈)  Various Artists  GN1500,GN2200   

        release  
236    20160707  
1782   20150115  
2072   20160707  
3146   20160311  
3525   20160311  
...         ...  
39698  20160113  
41324  20160707  
41347  20160707  
41820  20160707  
42920  20160707  

[69 rows x 6 columns]

In [26]:
meta[meta.song_name.str.contains('로또')]

lyric      id song_name  \
27317  당첨된다 당첨된다 로또 1등 당첨된다 좋은 꿈 꾸면 한 번 사봐요 좋은 일이 생길거...  543539     로또당첨송   

      artist   genre   release  
27317   썬차일드  GN0200  20151216

In [27]:
meta[meta.song_name.str.contains('생일')]

lyric      id  \
5113   왜 내가 더 두근대는지 왜 내가 더 기대하는지 하나 늘어난 촛불이 어색하지만 변함없...  205586   
7502   생일 축하해 내 사랑 생일 축하해 내 사랑 오늘은 내가 사랑하는 그녀의 생일이에요 ...  246761   
13093  고양이와 맥주 좋아하는 그대 태어난 오늘 장미 한 가득 이 계절 보다 더 아름다운 ...   44860   
17213  초가 꺼지겠지 소원을 다 빌면은 웃는 얼굴로 말을 하겠지 정말 고맙다고 초가 다 꺼...  377700   
17902  생일 축하해요 그대 생일 축하해요 바로 오늘 기다리던 날이네요 생일 축하해요 태어나...  417609   
19000  Happy birthday to you Happy birthday to you Ha...  432992   
20421  야호 드디어 오늘이다 요~콩순이 오늘이 뭔데? 음~ 오늘은 오늘은 내 생일 엄마 아...  452986   
20579  몰래 적어보는 그날의 List 달력 위엔 나만 아는 표시 어린아이처럼 설레는 느낌 ...  455072   
23779  생일을 축하해 yeah 프린세스 프링 프링 프링 나의 프린세스 프링 생일왕국의 프린...  486838   
26806  생일을 핑계로 너의 번홀 누르고 태연하게 축하한다 하며 애초에 답장은 바라지도 않듯...  534713   
27801  생일을 축하하오 생일을 축하하오 밤이 깊어 당신 꿈속에 닿지 못해도 생일을 축하하오...  550986   
27879  꿈에서라도 단 하루라 해도 내 운명의 남잘 꼭 만나고 싶어 생각만으론 싫어 남자들이...  551971   
28168  한 걸음도 다가 설 수 없었던 내 마음을 알아 주기를 얼마나 바라고 바래 왔는지 눈...  556438   
29552  너의 생일파티에서 드디어 다가온 너의 생일 입을 옷도 봐놨어 선물도 사놨어 넌 뭘 ...  579057   
35532  내가 사랑하는 네가 태어난 날에 난 노랠 불러 주고파 너 옆에 있어 주고파 내가 사...  658085   
35737  키가 작았었지 단 한 번도 눈에 띈 적도 없지 Wo wo wo wo wo wo wo...  660967   
40268  우리 꿈속에서 만날까요 오늘은 꼭 얘기해요 우리 기억속에 빠졌어요 그냥 밥먹다가 생...  108686   
40871  생일 축하합니다 생일 축하합니다 사랑하는 헬리의 생일 축하합니다 생일 축하합니다 생...  117646   

                                      song_name  \
5113                            생일선물 (Feat. 백산)   
7502                                     생일 축하해   
13093                                     생일축하해   
17213                         생일소원 (Feat. 스텔라장)   
17902                  생일 축하해요 (Happy Birthday)   
19000                     헬리의 생일 (English Ver.)   
20421                                 콩순이 생일축하송   
20579                           너의 생일 (One Day)   
23779                             생일왕국의 프린세스 프링   
26806                        생일을 핑계로 (Feat. 이레)   
27801                                  생일을 축하하오   
27879  하늘에서 남자들이 비처럼 내려와 (밤에 피는 장미, 축하해요 생일케이크)   
28168                          아버지 (축하해요 생일케이크)   
29552                                   너의 생일파티   
35532                                     생일 노래   
35737                       빠른 생일 (Born In Feb)   
40268                                   생일 축하해요   
40871                                    헬리의 생일   

                                         artist          genre   release  
5113                                        정민혁         GN0300  20180312  
7502                                리누 (Lee-Nu)         GN0100  20171214  
13093                                 에이브 (AEV)         GN0800  20190518  
17213                                    리차드파커스         GN0400  20180422  
17902                                       유지희  GN0500,GN0800  20160415  
19000                      로보카폴리 (Robocar POLI)  GN1500,GN2200  20170705  
20421                                       콩순이  GN1500,GN2200  20171113  
20579                              태연 (TAEYEON)  GN0400,GN2500  20180618  
23779                                   황정미,서미래  GN1500,GN2200  20160601  
26806                                        귀동         GN0100  20180919  
27801                                       마리슈  GN0500,GN0800  20161011  
27879                           신효범,주희 (Joohee)         GN0100  20150823  
28168                               주희 (Joohee)         GN0100  20150823  
29552  Esenswings X East Frog (이센스윙스 X 이스트 프로그)  GN0500,GN0300  20190522  
35532                                        민수  GN0500,GN0100  20180531  
35737                                  스티 (STi)  GN0500,GN0300  20150223  
40268                                      TAEK  GN0500,GN0400  20181115  
40871                      로보카폴리 (Robocar POLI)  GN1500,GN2200  20170705

In [20]:
meta[meta.genre=='GN3000']

Empty DataFrame
Columns: [lyric, id, song_name, artist, genre, release]
Index: []

In [19]:
genre = pd.read_csv("genre_gn_all.tsv",sep = '\t')
genre[genre['genre_id'].str.contains('^.*00$', regex=True)]

genre_id       genre
0     GN0100         발라드
6     GN0200          댄스
12    GN0300        랩/힙합
18    GN0400    R&B/Soul
22    GN0500        인디음악
32    GN0600        록/메탈
39    GN0700        성인가요
50    GN0800      포크/블루스
56    GN0900         POP
65    GN1000        록/메탈
80    GN1100      일렉트로니카
90    GN1200        랩/힙합
100   GN1300    R&B/Soul
109   GN1400  포크/블루스/컨트리
117   GN1500         OST
128   GN1600         클래식
144   GN1700          재즈
155   GN1800        뉴에이지
163   GN1900       J-POP
176   GN2000        월드뮤직
187   GN2100         CCM
198   GN2200      어린이/태교
215   GN2300        종교음악
218   GN2400          국악
225   GN2500         아이돌
232   GN2600      일렉트로니카
237   GN2700         EDM
242   GN2800       뮤직테라피
249   GN2900         뮤지컬
253   GN3000       크리스마스

In [6]:
import pandas as pd
m = pd.read_csv('infer/2015meta.csv')
m.to_csv('infer/2015meta1.csv',index=False,encoding='utf-8')